### ISSUE TITLE
BigSur Compatibility ?

### ISSUE THREAD

**Issue by areeb111** [RomanSmolka/finder-new-file#1]
I am using this app for the first time, But the extension is .applescript, Is that normal to rename it to .app ?
Anyway I have tried it in Big Sur it's not working.

**Comment by 7stud** [comment]
> I am using this app for the first time, But the extension is .applescript, Is that normal to rename it to .app ?
> Anyway I have tried it in Big Sur it's not working.

I'm using macOS 12.3.1 Monterey (M1 Pro).  The front page says:

`Copy the "New File.app" to your Applications directory`

so you aren't touching the .applescript file.  The first thing you need to do is download the code from this repository.  There is a green Code button that allows you to select how you want to download the code.  The code will be downloaded to your computer into a folder named `finder-new-file`.  Inside that folder will be a file called `New File.app`.  That is the file you need to copy to your Applications directory.

Then you need to open two Finder windows, so that you can see both at the same time.  In the upper Finder window, navigate to your Applications folder so that you can see `New File.app`.  Now, select the lower Finder window, then look at the top of the window, and in the menu bar, select `View>Customize Toolbar`.  Now, in the upper Finder window, drag `New File.app` onto the Toolbar in the lower Finder window.  You should see a `+` icon appear, and you can drop it anywhere on the Toolbar.

Now, as to how it works: you CAN'T just select a folder in Finder, click the `+` icon and have the text file created in that folder.  Instead, you have to double click the folder so that Finder actually enters that folder, then click the '+' icon to create the text file in that folder.

**Comment by 7stud** [comment]
> Same questions I guess

See above.
